pipeline {
    agent {
        label 'master'
    }

    environment {
       mailRecipients = 'zeeshan.athar@nxb.com.pk'
    }

    stages {
        stage('Production Deployment') {
            when {
                branch 'main'
            }
            steps {
             script {
              echo 'Deploying to : Production'
              ansiblePlaybook become: true, colorized: true, credentialsId: 'ansible-login', disableHostKeyChecking: true, installation: 'ansible', inventory:'pipeline/hosts', playbook: 'pipeline/helmPlaybook.yaml'
            }
          }
        }
        stage('Staging Deployment') {
        when {
            branch 'testing'
        }
        steps {
         script {
          echo 'Deploying to : Staging'
          withCredentials([usernamePassword(credentialsId: 'dockerhublogin', usernameVariable: 'dh_username', passwordVariable: 'dh_password')]){
          ansiblePlaybook become: true, extras: '-e dh_username=$dh_username -e dh_password=$dh_password', colorized: true, credentialsId: 'ansible-login', disableHostKeyChecking: true, installation: 'ansible', inventory: 'pipeline/hosts', playbook: 'pipeline/playbook.yaml'
          }
        }
      }
    }
  }
}
